-- CreateEnum
CREATE TYPE "Niche" AS ENUM ('TECH', 'GAMING', 'BEAUTY', 'FASHION', 'FITNESS', 'FINANCE', 'FOOD', 'TRAVEL', 'LIFESTYLE', 'EDUCATION', 'SPORTS', 'MUSIC', 'COMEDY', 'BUSINESS', 'HEALTH_WELLNESS');

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "niches" "Niche"[];
